name: protekfm
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ UI Dependencies
  curved_navigation_bar: ^1.0.6
  fl_chart: ^0.63.0
  cupertino_icons: ^1.0.6

  # ✅ State Management & Navigation
  flutter_bloc: ^8.1.3
  go_router: ^12.1.3
  provider: ^6.1.2

  # ✅ Image Handling
  image_picker: ^1.0.7

  # ✅ Splash Screen
  flutter_native_splash: ^2.3.2

  # ✅ Date & Calendar
  intl: ^0.18.1
  table_calendar: ^3.0.9

  # ✅ Shared Preferences
  shared_preferences: ^2.2.2

  # ✅ Path Provider
  path_provider: ^2.1.2

  # ✅ Phone Number Input
  intl_phone_field: ^3.1.0

  # ✅ File Picker
  file_picker: ^8.0.0

  # ✅ PDF Generation
  printing: ^5.6.0
  pdf: ^3.8.0

  # ✅ Open File
  open_file: ^3.2.1

  # ✅ Firebase Dependencies
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.5

  # ✅ Secure Storage for PIN & Biometric Authentication
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7

  # ✅ Vibration Feedback
  vibration: ^1.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/black-textured-wallpaper.png
    - assets/images/logo.png

# ✅ Splash Screen Configuration
flutter_native_splash:
  android: true
  ios: true
  image: assets/images/logo.png
  background_image: assets/images/black-textured-wallpaper.png
